version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      ports:
      - 5440:5640
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: ["-Djboss.http.port=8085"]
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8085:8085
      depends_on:
        - postgres